% Contains all the Global variables for TV white space communication in
% WARP boards
% 
% Author: Sanjib Sur
% Institute: University of Wisconsin - Madison
% Version: 0.0.1
% Last modified: 05/21/2014
% 
% Comments: This file contains all the global variables used across
% different files and functions of the TV white space PHY layer
% implementation which uses WURC + WARP boards.
% 
% 

global SIMSNR DEBUG_ON useFakeChannel VERBOSE1 VERBOSE2 USESIM osamp ...
    totalDataPkts Txparams Rxparams Timeparams STF STF_time LTF LTF_time LTF_shift Preamble Payload Packet ...
    STFcorrThrsh padding_size Padding TRACE_DRIVEN TRACE_COLLECT ...
    channel_trace_file numRxNode numTxNode...
    WARPLab_TxDelay WARPLab_TxLength WARPLab_CarrierChannel ...
    WARPLab_TxGain_RF WARPLab_TxGain_BB WARPLab_RxGain_BB ...
    WARPLab_RxGain_RF WARPLab_Frequency WURC repeat_STF_cnt data_to_subcarrier_map ...
    left_guard_len right_guard_len pilot_position inbits outbits hmodem hdemodem iFreq ...
    usePilotComp symb2BitNum TxConstellation RxConstellation ...
    WARPLab_node_tx WARPLab_node_rx WARPLab_RF_vector WARPLab_eth_trig Fc measured_CFO;